coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080

query.max-memory-per-node=256MB
memory.heap-headroom-per-node=128MB

task.max-writer-count=1
task.concurrency=2

spill-enabled=true
spiller-spill-path=/tmp/trino-spill
